# Generated by Django 5.2.7 on 2025-11-11 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='face_images/%Y/%m/%d/')),
                ('sex', models.CharField(max_length=20)),
                ('sex_confidence', models.FloatField()),
                ('eyes', models.CharField(max_length=50)),
                ('eyes_confidence', models.FloatField()),
                ('race', models.CharField(max_length=50)),
                ('race_confidence', models.FloatField()),
                ('hair', models.CharField(max_length=50)),
                ('hair_confidence', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Analisis facial',
                'verbose_name_plural': 'Analisis faciales',
                'db_table': 'face_analysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
